// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"student/internal/biz"
	"student/internal/conf"
	"student/internal/data"
	"student/internal/server"
	"student/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger, confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRdb(confData, logger)
	redisClient := data.NewRedisClient(client, logger)
	studentRepo := data.NewStudentRepo(dataData, logger, redisClient)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	studentService := service.NewStudentService(studentUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, studentService, logger)
	httpServer := server.NewHTTPServer(confServer, studentService, logger)
	app := newApp(logger, grpcServer, httpServer, studentRepo)
	return app, func() {
		cleanup()
	}, nil
}
